INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOB_TITLE, GENDER, DATE_OF_BIRTH) VALUES
('Petr', 'Petrov', 1, 'Manager','MALE' , '19-09-1985'),
('Mariya', 'Ivanova', 2, 'Engineer', 'FEMALE', '04-07-1987');


